### ISSUE TITLE
post processed blog entries

### ISSUE THREAD

**Issue by WebReflection** [casualjs/blog#1]
I was going to point at few mistakes you published on your [Part 1 entry](http://casualjavascript.com/javascript/es6/haskell/native/implementation/2015/11/12/haskell-in-es6-part-1.html) , and I haven't read part 2 yet, and realized you are pushing already transformed markdown  in  here, which makes basically pointless and impossible to file an issue and correct some code.

Are you planning to change this and upload also originals or your posts are destined to be "wrong" forever?

I mean, there's no even a way to comment in there ... let me introduce you [Disqus](https://disqus.com/home/explore/) if I might

**Comment by mateogianolio** [comment]
Hey, I have plans to add Disqus. In the meantime you can find the source and file an issue [here](https://github.com/casualjs/f).

**Comment by WebReflection** [comment]
Maybe I didn't explain myself that good ... you have errors in your examples shown in the blog post, not in the lib itself ( or at least this is not the reason I've  filed an issue **here** and not there )

**Comment by mateogianolio** [comment]
Ah, okay. Which errors?

**Comment by WebReflection** [comment]
to name just one, your very first example is broken syntax

```js
export function comp (...fs) => {
  return (v, ...args) =>
    fs.reduceRight(
      (g, f) => f(g, ...args), v
    );
}
```

I'm not going through all others until I have a way to diff them. Please publish the md source of your posts too if your plan was to have a GitHub based blog/site.

Otherwise, if not, think about how developers could help you fix non  tested code in your examples.
Not kidding, there are many syntax errors and some misleading piece of code in there.

Cheers

**Comment by mateogianolio** [comment]
From [`ƒ.js`](https://github.com/casualjs/f/blob/master/ƒ.js):
```javascript
/**
 * Function composition
 * @param ...fs functions to compose
 * @return composed function
 **/
export function comp (...fs) {
  return (v, ...args) =>
    fs.reduceRight(
      (g, f) => f(g, ...args), v
    );
}
```

From [`test/test.js`](https://github.com/casualjs/f/blob/master/test/test.js):

```javascript
var add = x => x + x,
    pow = x => x * x,
    inv = x => 1 / x,
    comp = ƒ.comp(add, pow, inv);

assert.equal(2, comp(1));
assert.equal(1/8, comp(4));
```

I'm not sure how this differs from the blog's version.

**Comment by WebReflection** [comment]
that's because you don't have post sources in here and you cannot see the diff ... which is my exact point.

![screenshot from 2015-11-20 01-22-33](https://cloud.githubusercontent.com/assets/85749/11288556/6f138980-8f25-11e5-8b3e-4ec41c130ddf.png)


you can see that in your very same post http://casualjavascript.com/javascript/es6/haskell/native/implementation/2015/11/12/haskell-in-es6-part-1.html

**Comment by WebReflection** [comment]
To be extra clear:  your code is OK,  your blog post is full of Syntax errors ...

**Comment by WebReflection** [comment]
another example ...

![screenshot from 2015-11-20 01-26-32](https://cloud.githubusercontent.com/assets/85749/11288605/e9b540c0-8f25-11e5-91c9-85e95585188b.png)

**Comment by WebReflection** [comment]
actually even worst, it feels like you haven't test a single example in there .. you missed also the colon  after the `three` declaration .... now, do you understand why I've opened here an issue that you closed at speed  light without even seeing the problem?

It's you posting, I don't mind, but I think it was a good "feature request" from a user.

Now I'm going to sleep, take care.

**Comment by mateogianolio** [comment]
Fixed. Let me know if you find anything more.

**Comment by WebReflection** [comment]
I won't, because there is a bigger problem here and I've filed a bug for it.

Take care

**Comment by mateogianolio** [comment]
Okay :) take care
